# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hello there, buddy boy"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: View Directory
        run: |
          ls -la
          
      - name: deploy-via-scp
        # You may pin to the exact commit or the version.
        # uses: horochx/deploy-via-scp@bf9a636d9a475a714e375ba1cc455d1c5c861aef
        uses: horochx/deploy-via-scp@v1.0.1
        with:
            # Local file path
           local: /
           # Remote file path
           remote: /
           # Remote server address
           host: 104.248.3.8
           # Remote server port
           port: 22
           # Remote server user
           user: ${{ secrets.SSH_USER }}
           # Remote server private key
           key: ${{ secrets.KEY }}
